#!/usr/bin/env bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
export DEPLOY_ROOT_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

source "$DEPLOY_ROOT_DIR/src/common.bash"

ensure_deploy_variables
create_kubeconfig

if [[ ! -f templates/config.tpl ]]; then
  echo "No template file found in ./templates/config.tpl ..."
  exit 1
fi

echo "Deploying $CI_ENVIRONMENT_SLUG (release name: $releases_name) with $CI_REGISTRY_IMAGE:$CI_REGISTRY_TAG..."
Generate-yaml
kubectl apply -f etc/ -n $KUBE_NAMESPACE

echo ""

