#! /usr/bin/env python
# -*- coding: utf-8 -*-

from jinja2 import Environment, FileSystemLoader
import os
import yaml
import codecs

def generatefile(srcfile,tplpath,tplfile):
  #Load data from YAML into Python dictionary
  my_data = yaml.load(open( etc_path + '/' + srcfile))
  global_data = yaml.load(open( etc_path + '/parent/global.yml'))
  config_data = dict(my_data, **global_data)

  #Load Jinja2 template
  env = Environment(loader = FileSystemLoader(tpl_path), trim_blocks=True, lstrip_blocks=True)
  template = env.get_template(tplfile)

  #Render the template with data and print the output
  return template.render(config_data)


#list etc files
etc_path = "./etc"
etc_files = os.listdir(etc_path)
tpl_path = "./templates"
tpl_file = "config.tpl"
k8s_path = "./k8s"

if not os.path.exists(k8s_path):
   os.mkdir(k8s_path)

for file in etc_files:
    if os.path.isfile(etc_path + '/' + file):
       content = generatefile(file,tpl_path,tpl_file)
       k8s_file = codecs.open( k8s_path + '/' + file, 'w', 'utf-8')
       k8s_file.write(content)
       k8s_file.close()


